export default class URLCredentialContract {
  constructor() {}

  public static _ID: string = "_id"

  public static _COUNT: string = "_count";

  public static TABLE_NAME: string = "credential";

  public static COLUMN_NAME_USERNAME: string = "username";

  public static COLUMN_NAME_PASSWORD: string = "password";

  public static COLUMN_NAME_PROTECTION_SPACE_ID: string = "protection_space_id";
}