export default class URLProtectionSpaceContract {
  constructor() {}

  public static _ID: string = "_id"

  public static _COUNT: string = "_count";

  public static TABLE_NAME: string = "protection_space";

  public static COLUMN_NAME_HOST: string = "host";

  public static COLUMN_NAME_PROTOCOL: string = "protocol";

  public static COLUMN_NAME_REALM: string = "realm";

  public static COLUMN_NAME_PORT: string = "port";

}